

- name: install packages
  win_chocolatey: name={{ item }} state=present
  with_items:
    - git
    - atom
    - jetbrainstoolbox
    - postman
    - nvm
    - jdk8
    # - jdk9
    - ant
    - maven
    - gradle
    # - dbeaver-ee
    - dotnetcore-sdk
    - visualstudio2015community
    - sql-server-management-studio
    # - awscli
    # - kubernetes-cli
    # - gcloudsdk
